
---
title: "Synthetic Germany"
output: html_notebook
---

```{r}

#packages needed for the code

# Data manipulation
library(dplyr)      # For data manipulation
library(tidyr)      # For reshaping data

# Synthetic control method
library(Synth)      # For synthetic control method

# Data visualization
library(ggplot2)    # For data visualization

# Read in data
library(readr)      # For reading CSV data

library(readxl)


```

```{r}
setwd("C:/Users/gabu/Documents/Germany")


# Get the list of sheets
sheets <- excel_sheets("Database synthetic GER.xlsx")

print(sheets)
```




```{r}

library(readxl)

# Read the data from the "Inflation" sheet
inflation_df <- read_excel("Database synthetic GER.xlsx", sheet = "Inflation")

# View the extracted data frame
View(inflation_df)




```


```{r}
# Load necessary libraries
library(tidyr)
library(dplyr)

# Convert data to long format: years as rows, 'Country Code' column remains unchanged
long_data <- inflation_df %>%
  gather(key = "Date", value = "Value", -`Country Code`)

# Pivot the long data to wide format: countries as columns
wide_data <- long_data %>%
  spread(key = `Country Code`, value = Value)

View(wide_data)

```


```{r}
data_types <- sapply(wide_data, class)
print(data_types) # Displays the data type of each column

```

```{r}

# Count NAs in each column
na_count_per_column <- sapply(wide_data, function(col) sum(is.na(col)))

# Print the NA count for each column
print(na_count_per_column)



```

